dataset = [
{"word": "Hund", "meaning": "dog", "mnemonic": "A HUND reminds me of a hound dog.", "level": 1},
{"word": "Katze", "meaning": "cat", "mnemonic": "KATZE sounds like 'cuts ya', playful like a cat.", "level": 1},
{"word": "Apfel", "meaning": "apple", "mnemonic": "APFEL sounds like 'apple'.", "level": 1},
{"word": "Brot", "meaning": "bread", "mnemonic": "Think of BROT as a warm loaf you brought home.", "level": 1},
{"word": "Milch", "meaning": "milk", "mnemonic": "MILCH sounds like milk with a ch – creamy and white.", "level": 1},
{"word": "Buch", "meaning": "book", "mnemonic": "BUCH is a book with a strong German snap.", "level": 1},
{"word": "Haus", "meaning": "house", "mnemonic": "HAUS looks and sounds just like house.", "level": 1},
{"word": "Auto", "meaning": "car", "mnemonic": "AUTO is short for automobile.", "level": 1},
{"word": "Blume", "meaning": "flower", "mnemonic": "BLUME reminds you of a blooming flower.", "level": 1},
{"word": "Vogel", "meaning": "bird", "mnemonic": "VOGEL rhymes with 'vocal' – like birds singing.", "level": 1},
{"word": "Fisch", "meaning": "fish", "mnemonic": "FISCH swims like a fish.", "level": 1},
{"word": "Wasser", "meaning": "water", "mnemonic": "WASSER splashes like water in a glass.", "level": 1},
{"word": "Stuhl", "meaning": "chair", "mnemonic": "STUHL sounds like stool – something you sit on.", "level": 1},
{"word": "Tisch", "meaning": "table", "mnemonic": "TISCH rhymes with 'dish', which goes on the table.", "level": 1},
{"word": "Lampe", "meaning": "lamp", "mnemonic": "LAMPE is just like lamp with an extra ‘e’.", "level": 1},
{"word": "Schule", "meaning": "school", "mnemonic": "SCHULE sounds like school – desks and bells.", "level": 1},
{"word": "Freund", "meaning": "friend", "mnemonic": "FREUND sounds like friend – someone friendly.", "level": 1},
{"word": "Fenster", "meaning": "window", "mnemonic": "Imagine cleaning your FENSTER and seeing the stars.", "level": 1},
{"word": "Tür", "meaning": "door", "mnemonic": "TÜR sounds like tour – go through a door on a tour.", "level": 1},
{"word": "Boden", "meaning": "floor", "mnemonic": "Think of falling on your bottom – onto the BODEN.", "level": 1},
{"word": "Zimmer", "meaning": "room", "mnemonic": "ZIMMER like Zimmer frame in a care home room.", "level": 1},
{"word": "Stadt", "meaning": "city", "mnemonic": "STADT sounds like 'stadium' – found in cities.", "level": 1},
{"word": "Straße", "meaning": "street", "mnemonic": "STRAßE looks like a street sign.", "level": 1},
{"word": "Bleistift", "meaning": "pencil", "mnemonic": "BLEI = lead, STIFT = stick – a pencil!", "level": 1},
{"word": "Hemd", "meaning": "shirt", "mnemonic": "HEMD sounds like ‘hemmed’ – the edge of a shirt.", "level": 1},
{"word": "Kopf", "meaning": "head", "mnemonic": "KOPF like 'cap' on your head.", "level": 1},
{"word": "Hand", "meaning": "hand", "mnemonic": "HAND is exactly what it looks like – your hand.", "level": 1},
{"word": "Bein", "meaning": "leg", "mnemonic": "BEIN sounds like 'bendy' – bend your leg.", "level": 1},
{"word": "Fuß", "meaning": "foot", "mnemonic": "FUß steps forward like a foot.", "level": 1},
{"word": "Auge", "meaning": "eye", "mnemonic": "AUGE sounds like ‘eyeglasses’.", "level": 1},
{"word": "Nase", "meaning": "nose", "mnemonic": "NASAL sounds like NOSE – easy one!", "level": 1},
{"word": "Mund", "meaning": "mouth", "mnemonic": "MUND sounds like munch – with your mouth.", "level": 1},
{"word": "Zahn", "meaning": "tooth", "mnemonic": "ZAHN sounds like 'zany' tooth fairy!", "level": 1},
{"word": "Herz", "meaning": "heart", "mnemonic": "HERZ is the heart – think of love and emotion.", "level": 1},
{"word": "Bauch", "meaning": "belly", "mnemonic": "BAUCH sounds like 'belch' – from your belly.", "level": 1},
{"word": "Küche", "meaning": "kitchen", "mnemonic": "KÜCHE sounds like cooking – where food happens.", "level": 1},
{"word": "Bad", "meaning": "bath", "mnemonic": "BAD is not bad – it's your bath!", "level": 1},
{"word": "Garten", "meaning": "garden", "mnemonic": "GARTEN is a garden – full of green!", "level": 1},
{"word": "Löffel", "meaning": "spoon", "mnemonic": "LÖFFEL scoops like a little shovel.", "level": 1},
{"word": "Gabel", "meaning": "fork", "mnemonic": "GABEL stabs your salad – it's a fork.", "level": 1},
{"word": "Messer", "meaning": "knife", "mnemonic": "MESSER cuts like a mess-maker.", "level": 1},
{"word": "Bett", "meaning": "bed", "mnemonic": "BETT is bed – where you rest your head.", "level": 1},
{"word": "Uhr", "meaning": "clock", "mnemonic": "UHR ticks like a wristwatch – a clock.", "level": 1},
{"word": "Computer", "meaning": "computer", "mnemonic": "Same word – you're using one now!", "level": 1},
{"word": "Telefon", "meaning": "phone", "mnemonic": "TELEFON rings just like 'telephone'.", "level": 1},
{"word": "Karte", "meaning": "map/card", "mnemonic": "KARTE = card or map – think boarding pass.", "level": 1},
{"word": "Bahn", "meaning": "train", "mnemonic": "BAHN sounds like 'bahn station' – train time.", "level": 1},
{"word": "Flugzeug", "meaning": "airplane", "mnemonic": "FLUG = flight, ZEUG = thing – flying thing!", "level": 1},
{"word": "Auto", "meaning": "car", "mnemonic": "AUTO like auto-mobile.", "level": 1},
  {"word": "Wie war dein Tag?", "meaning": "How was your day?", "mnemonic": "WAR = was. Imagine asking a friend over coffee.", "level": 2},
    {"word": "Was möchtest du tun?", "meaning": "What do you want to do?", "mnemonic": "MÖCHTEST = want. Picture planning an activity.", "level": 2},
    {"word": "Kannst du mir helfen?", "meaning": "Can you help me?", "mnemonic": "HELFEN = help. Think of asking for directions.", "level": 2},
    {"word": "Ich habe eine Frage.", "meaning": "I have a question.", "mnemonic": "FRAGE = question. Raising your hand in class.", "level": 2},
    {"word": "Das verstehe ich nicht.", "meaning": "I don’t understand that.", "mnemonic": "VERSTEHEN = understand. Confused head shake.", "level": 2},
    {"word": "Kannst du das erklären?", "meaning": "Can you explain that?", "mnemonic": "ERKLÄREN = explain. Pointing at a confusing map.", "level": 2},
    {"word": "Wie spät ist es jetzt?", "meaning": "What time is it now?", "mnemonic": "JETZT = now. Checking your watch urgently.", "level": 2},
    {"word": "Wo sind die Toiletten?", "meaning": "Where are the toilets?", "mnemonic": "TOILETTEN = toilets. Imagine dancing in urgency.", "level": 2},
    {"word": "Ich bin bereit!", "meaning": "I’m ready!", "mnemonic": "BEREIT = ready. Picture standing by the door.", "level": 2},
    {"word": "Das ist eine gute Idee!", "meaning": "That’s a good idea!", "mnemonic": "IDEE = idea. Lightbulb moment!", "level": 2},
    {"word": "Ich bin nicht sicher.", "meaning": "I’m not sure.", "mnemonic": "SICHER = sure. Shrugging shoulders.", "level": 2},
    {"word": "Warte einen Moment!", "meaning": "Wait a moment!", "mnemonic": "WARTE = wait. Holding up a finger.", "level": 2},
    {"word": "Ich bin so glücklich!", "meaning": "I’m so happy!", "mnemonic": "GLÜCKLICH = happy. Big smile!", "level": 2},
    {"word": "Das ist sehr nett von dir.", "meaning": "That’s very kind of you.", "mnemonic": "NETT = kind. Receiving a gift.", "level": 2},
    {"word": "Kann ich dir vertrauen?", "meaning": "Can I trust you?", "mnemonic": "VERTRAUEN = trust. Handshake.", "level": 2},
    {"word": "Ich habe es vergessen.", "meaning": "I forgot.", "mnemonic": "VERGESSEN = forget. Slapping forehead.", "level": 2},
    {"word": "Mach dir keine Sorgen!", "meaning": "Don’t worry!", "mnemonic": "SORGEN = worries. Patting someone’s back.", "level": 2},
    {"word": "Das ist mein Lieblings…", "meaning": "That’s my favorite…", "mnemonic": "LIEBLINGS = favorite. Heart eyes!", "level": 2},
    {"word": "Ich bin beschäftigt.", "meaning": "I’m busy.", "mnemonic": "BESCHÄFTIGT = busy. Typing on a laptop.", "level": 2},
    {"word": "Kannst du langsamer sprechen?", "meaning": "Can you speak slower?", "mnemonic": "LANGSAMER = slower. Slow-motion hand gesture.", "level": 2},
    {"word": "Ich brauche eine Pause.", "meaning": "I need a break.", "mnemonic": "PAUSE = break. Sitting on a bench.", "level": 2},
    {"word": "Wie geht es deiner Familie?", "meaning": "How is your family?", "mnemonic": "FAMILIE = family. Picture a family photo.", "level": 2},
    {"word": "Ich vermisse dich.", "meaning": "I miss you.", "mnemonic": "VERMISSEN = miss. Heartfelt text message.", "level": 2},
    {"word": "Kann ich das probieren?", "meaning": "Can I try that?", "mnemonic": "PROBIEREN = try. Reaching for a sample.", "level": 2},
    {"word": "Das ist zu teuer.", "meaning": "That’s too expensive.", "mnemonic": "TEUER = expensive. Gasping at a price tag.", "level": 2},
    {"word": "Ich habe Hunger.", "meaning": "I’m hungry.", "mnemonic": "HUNGER = hunger. Stomach growling.", "level": 2},
    {"word": "Ich habe Durst.", "meaning": "I’m thirsty.", "mnemonic": "DURST = thirst. Mimicking drinking.", "level": 2},
    {"word": "Wo ist der nächste Supermarkt?", "meaning": "Where’s the nearest supermarket?", "mnemonic": "SUPERMARKT = supermarket. Holding grocery bags.", "level": 2},
    {"word": "Kannst du das wiederholen?", "meaning": "Can you repeat that?", "mnemonic": "WIEDERHOLEN = repeat. Circular hand motion.", "level": 2},
    {"word": "Ich bin verloren.", "meaning": "I’m lost.", "mnemonic": "VERLOREN = lost. Looking at a map upside down.", "level": 2},
    {"word": "Wie viel kostet das?", "meaning": "How much does that cost?", "mnemonic": "KOSTET = costs. Pointing at a price.", "level": 2},
    {"word": "Ich möchte bezahlen.", "meaning": "I’d like to pay.", "mnemonic": "BEZAHLEN = pay. Handing over cash.", "level": 2},
    {"word": "Kann ich mit Kreditkarte zahlen?", "meaning": "Can I pay with a credit card?", "mnemonic": "KREDITKARTE = credit card. Swiping a card.", "level": 2},
    {"word": "Das ist fantastisch!", "meaning": "That’s fantastic!", "mnemonic": "FANTASTISCH = fantastic. Jazz hands!", "level": 2},
    {"word": "Ich bin enttäuscht.", "meaning": "I’m disappointed.", "mnemonic": "ENTTÄUSCHT = disappointed. Frowning face.", "level": 2},
    {"word": "Kannst du das übersetzen?", "meaning": "Can you translate this?", "mnemonic": "ÜBERSETZEN = translate. Pointing at a dictionary.", "level": 2},
    {"word": "Ich bin erkältet.", "meaning": "I have a cold.", "mnemonic": "ERKÄLTET = cold. Sneezing into a tissue.", "level": 2},
    {"word": "Gute Fahrt!", "meaning": "Have a good trip!", "mnemonic": "FAHRT = trip. Waving at a departing train.", "level": 2},
    {"word": "Ich bin aufgeregt.", "meaning": "I’m excited.", "mnemonic": "AUFGEREGT = excited. Jumping up and down.", "level": 2},
    {"word": "Das ist langweilig.", "meaning": "That’s boring.", "mnemonic": "LANGWEILIG = boring. Yawning dramatically.", "level": 2},
    {"word": "Ich bin müde.", "meaning": "I’m tired.", "mnemonic": "MÜDE = tired. Rubbing eyes.", "level": 2},
    {"word": "Kannst du mir das geben?", "meaning": "Can you give me that?", "mnemonic": "GEBEN = give. Reaching out your hand.", "level": 2},
    {"word": "Ich habe es geschafft!", "meaning": "I did it!", "mnemonic": "GESCHAFFT = accomplished. Fist pump!", "level": 2},
    {"word": "Das ist unfair!", "meaning": "That’s unfair!", "mnemonic": "UNFAIR = unfair. Crossing arms angrily.", "level": 2},
    {"word": "Ich bin überrascht.", "meaning": "I’m surprised.", "mnemonic": "ÜBERRASCHT = surprised. Wide-eyed emoji face.", "level": 2},
    {"word": "Kann ich dich anrufen?", "meaning": "Can I call you?", "mnemonic": "ANRUFEN = call. Mimicking phone to ear.", "level": 2},
    {"word": "Ich bin beschäftigt.", "meaning": "I’m busy.", "mnemonic": "BESCHÄFTIGT = busy. Typing on a laptop.", "level": 2},
    {"word": "Ich bin in Eile.", "meaning": "I’m in a hurry.", "mnemonic": "EILE = hurry. Running to catch a bus.", "level": 2},
    {"word": "Das ist gefährlich.", "meaning": "That’s dangerous.", "mnemonic": "GEFÄHRLICH = dangerous. Warning sign.", "level": 2},
    {"word": "Ich bin glücklich.", "meaning": "I’m happy.", "mnemonic": "GLÜCKLICH = happy. Smiling sun.", "level": 2},
    {"word": "Kannst du das empfehlen?", "meaning": "Can you recommend that?", "mnemonic": "EMPFHELEN = recommend. Thumbs up.", "level": 2},
    {"word": "Ich bin traurig.", "meaning": "I’m sad.", "mnemonic": "TRAURIG = sad. Drooping shoulders.", "level": 2},
    {"word": "Das ist einfach.", "meaning": "That’s easy.", "mnemonic": "EINFACH = easy. Casual shrug.", "level": 2},
    {"word": "Das ist schwierig.", "meaning": "That’s difficult.", "mnemonic": "SCHWIERIG = difficult. Scratching head.", "level": 2},
    {"word": "Ich bin beeindruckt.", "meaning": "I’m impressed.", "mnemonic": "BEEINDRUCKT = impressed. Slow clap.", "level": 2},
    {"word": "Kannst du warten?", "meaning": "Can you wait?", "mnemonic": "WARTEN = wait. Tapping foot impatiently.", "level": 2},
    {"word": "Ich bin fertig.", "meaning": "I’m finished.", "mnemonic": "FERTIG = finished. Brushing hands together.", "level": 2},
{"word": "Guten Morgen", "meaning": "Good morning", "mnemonic": "GUTEN = good, MORGEN = morning. Picture someone greeting you with coffee.", "level": 2},
{"word": "Guten Tag", "meaning": "Good day", "mnemonic": "Say GUTEN TAG like tipping your hat at noon.", "level": 2},
{"word": "Gute Nacht", "meaning": "Good night", "mnemonic": "GUTE NACHT = bedtime words before turning off the light.", "level": 2},
{"word": "Wie geht es dir?", "meaning": "How are you?", "mnemonic": "VEE GATE like opening a gate to ask how someone feels.", "level": 2},
{"word": "Ich heiße Anna.", "meaning": "My name is Anna.", "mnemonic": "ICH HEIßE sounds like 'Hi, I’m...' – easy intro.", "level": 2},
{"word": "Ich komme aus England.", "meaning": "I come from England.", "mnemonic": "KOMME AUS = come from. Imagine arriving from England.", "level": 2},
{"word": "Wie alt bist du?", "meaning": "How old are you?", "mnemonic": "ALT = old. Imagine candles on a cake!", "level": 2},
{"word": "Ich bin müde.", "meaning": "I’m tired.", "mnemonic": "MÜDE sounds like 'moody' from being tired.", "level": 2},
{"word": "Ich bin hungrig.", "meaning": "I’m hungry.", "mnemonic": "HUNGRIG = hungry. Stomach growling!", "level": 2},
{"word": "Ich bin durstig.", "meaning": "I’m thirsty.", "mnemonic": "DURSTIG sounds like 'dry throat' – need a drink!", "level": 2},
{"word": "Was machst du?", "meaning": "What are you doing?", "mnemonic": "WAS = what, MACHST = do. Asking about actions.", "level": 2},
{"word": "Ich lerne Deutsch.", "meaning": "I’m learning German.", "mnemonic": "LERNE = learn. Easy to remember!", "level": 2},
{"word": "Ich verstehe nicht.", "meaning": "I don’t understand.", "mnemonic": "VERSTEHE = understand, NICHT = not.", "level": 2},
{"word": "Sprechen Sie Englisch?", "meaning": "Do you speak English?", "mnemonic": "SPRECHEN = speak, ENGLISCH = English.", "level": 2},
{"word": "Können Sie das bitte wiederholen?", "meaning": "Can you repeat that, please?", "mnemonic": "WIEDERHOLEN = repeat. Imagine hitting rewind.", "level": 2},
{"word": "Wie spät ist es?", "meaning": "What time is it?", "mnemonic": "SPÄT = late. Looking at your watch.", "level": 2},
{"word": "Was ist das?", "meaning": "What is that?", "mnemonic": "Simple: WAS = what, DAS = that.", "level": 2},
{"word": "Wo wohnst du?", "meaning": "Where do you live?", "mnemonic": "WO = where, WOHNST = live. Think of your house.", "level": 2},
{"word": "Ich mag Musik.", "meaning": "I like music.", "mnemonic": "MAG = like, MUSIK = music. Think headphones.", "level": 2},
{"word": "Ich liebe dich.", "meaning": "I love you.", "mnemonic": "LIEBE = love, DICH = you. Romantic or sweet!", "level": 2},
{"word": "Mir ist kalt.", "meaning": "I’m cold.", "mnemonic": "KALT = cold. Imagine shivering in snow.", "level": 2},
{"word": "Mir ist heiß.", "meaning": "I’m hot.", "mnemonic": "HEIß = hot. Imagine wiping sweat.", "level": 2},
{"word": "Was kostet das?", "meaning": "How much does that cost?", "mnemonic": "KOSTET = cost. Looking at a price tag.", "level": 2},
{"word": "Ich habe keine Ahnung.", "meaning": "I have no idea.", "mnemonic": "KEINE AHNUNG = no clue. Shrugging shoulders.", "level": 2},
{"word": "Ich brauche Hilfe.", "meaning": "I need help.", "mnemonic": "BRAUCHE = need, HILFE = help. Think emergency.", "level": 2},
{"word": "Wo ist die Toilette?", "meaning": "Where is the toilet?", "mnemonic": "TOILETTE is easy. Picture asking urgently!", "level": 2},
{"word": "Entschuldigung!", "meaning": "Excuse me / Sorry!", "mnemonic": "Long word, short use – when bumping into someone.", "level": 2},
{"word": "Alles klar?", "meaning": "All clear? / Everything okay?", "mnemonic": "Literally 'everything clear?' – used casually.", "level": 2},
{"word": "Bis bald!", "meaning": "See you soon!", "mnemonic": "BIS BALD = until soon. Friendly farewell.", "level": 2},
{"word": "Gute Reise!", "meaning": "Have a good trip!", "mnemonic": "REISE = travel. Wishing someone well.", "level": 2},
{"word": "Guten Appetit!", "meaning": "Enjoy your meal!", "mnemonic": "APPETIT = appetite. Said before eating.", "level": 2},
{"word": "Schönen Tag noch!", "meaning": "Have a nice day!", "mnemonic": "SCHÖN = nice, TAG = day.", "level": 2},
{"word": "Ich bin krank.", "meaning": "I’m sick.", "mnemonic": "KRANK = ill. Imagine lying in bed.", "level": 2},
{"word": "Ich bin gesund.", "meaning": "I’m healthy.", "mnemonic": "GESUND = sound, strong, well.", "level": 2},
{"word": "Ich habe einen Termin.", "meaning": "I have an appointment.", "mnemonic": "TERMIN = appointment. Calendar reminder.", "level": 2},
{"word": "Es tut mir leid.", "meaning": "I’m sorry.", "mnemonic": "TUT MIR LEID = does me sorrow.", "level": 2},
{"word": "Ich bin beschäftigt.", "meaning": "I’m busy.", "mnemonic": "BESCHÄFTIGT = busy. Picture being buried in work.", "level": 2},
{"word": "Ich bin frei.", "meaning": "I’m free.", "mnemonic": "FREI = free. Like having no plans.", "level": 2},
{"word": "Ich arbeite hier.", "meaning": "I work here.", "mnemonic": "ARBEITE = work. Imagine pointing to your desk.", "level": 2},
{"word": "Ich bin Lehrer.", "meaning": "I am a teacher.", "mnemonic": "LEHR = to teach. Picture a blackboard.", "level": 2},
{"word": "Ich bin Student.", "meaning": "I’m a student.", "mnemonic": "STUDENT = student. Easy one!", "level": 2},
{"word": "Ich habe Durst.", "meaning": "I’m thirsty.", "mnemonic": "DURST = thirst. Dry mouth, need water.", "level": 2},
{"word": "Ich habe Hunger.", "meaning": "I’m hungry.", "mnemonic": "HUNGER = hunger. Growling stomach.", "level": 2},
{"word": "Ich weiß nicht.", "meaning": "I don’t know.", "mnemonic": "WEISS = know. 'I know not'.", "level": 2},
{"word": "Ich stimme zu.", "meaning": "I agree.", "mnemonic": "STIMME = voice, ZU = to. Giving your yes.", "level": 2},
{"word": "Ich stimme nicht zu.", "meaning": "I disagree.", "mnemonic": "Same phrase + NICHT = not.", "level": 2},
{"word": "Was bedeutet das?", "meaning": "What does that mean?", "mnemonic": "BEDEUTET = means. Asking for a definition.", "level": 2},
{"word": "Ich spreche nur ein bisschen Deutsch.", "meaning": "I only speak a little German.", "mnemonic": "BISSCHEN = a little. Picture small talk.", "level": 2},
{"word": "Ich möchte eine Tasse Kaffee.", "meaning": "I'd like a cup of coffee.", "mnemonic": "MÖCHTE = would like, TASSE = cup – imagine politely asking at a café.", "level": 3},
{"word": "Ich hätte gerne ein Bier vom Fass.", "meaning": "I’d like a draft beer.", "mnemonic": "BIER = beer, FASS = keg. Picture pointing to a tap at a bar.", "level": 3},
{"word": "Könnten Sie das bitte wiederholen?", "meaning": "Could you repeat that, please?", "mnemonic": "WIEDERHOLEN = repeat – imagine someone repeating slowly for you.", "level": 3},
{"word": "Ich habe meine Schlüssel verloren.", "meaning": "I lost my keys.", "mnemonic": "SCHLÜSSEL = keys, VERLOREN = lost – imagine patting all your pockets.", "level": 3},
{"word": "Es tut mir leid, ich spreche nicht gut Deutsch.", "meaning": "I’m sorry, I don’t speak German well.", "mnemonic": "TUT MIR LEID = I'm sorry. Picture apologising while struggling for words.", "level": 3},
{"word": "Könnten Sie bitte ein Foto von uns machen?", "meaning": "Could you take a photo of us, please?", "mnemonic": "MACHEN = make/do. Imagine holding out your phone to a stranger.", "level": 3},
{"word": "Ich möchte heute etwas Neues ausprobieren.", "meaning": "I want to try something new today.", "mnemonic": "AUSPROBIEREN = try out. Picture tasting a new food.", "level": 3},
{"word": "Ich bin seit drei Tagen hier.", "meaning": "I’ve been here for three days.", "mnemonic": "SEIT = since, DREI TAGEN = three days. Picture crossing off a calendar.", "level": 3},
{"word": "Gibt es hier in der Nähe einen Supermarkt?", "meaning": "Is there a supermarket nearby?", "mnemonic": "NÄHE = near. Imagine scanning the street for groceries.", "level": 3},
{"word": "Wo kann ich ein Taxi finden?", "meaning": "Where can I find a taxi?", "mnemonic": "FINDEN = find. Picture looking around a busy square.", "level": 3},
{"word": "Ich suche ein gutes Restaurant.", "meaning": "I’m looking for a good restaurant.", "mnemonic": "SUCHE = search. Picture scanning reviews on your phone.", "level": 3},
{"word": "Ich möchte bar bezahlen.", "meaning": "I’d like to pay in cash.", "mnemonic": "BAR = cash, BEZAHLEN = pay. Picture handing over notes.", "level": 3},
{"word": "Ich habe einen Tisch reserviert.", "meaning": "I have reserved a table.", "mnemonic": "TISCH = table, RESERVIERT = reserved. Picture your name on a reservation card.", "level": 3},
{"word": "Ich reise morgen nach Berlin.", "meaning": "I’m travelling to Berlin tomorrow.", "mnemonic": "REISE = travel, MORGEN = tomorrow. Picture your train ticket.", "level": 3},
{"word": "Ich brauche einen Arzt.", "meaning": "I need a doctor.", "mnemonic": "ARZT = doctor. Imagine urgently needing help.", "level": 3},
{"word": "Ich habe Zahnschmerzen.", "meaning": "I have a toothache.", "mnemonic": "ZAHN = tooth, SCHMERZEN = pain. Picture touching your cheek in pain.", "level": 3},
{"word": "Ich habe mich verlaufen.", "meaning": "I got lost.", "mnemonic": "VERLAUFEN = lost. Picture standing confused with a map.", "level": 3},
{"word": "Ich bin allergisch gegen Nüsse.", "meaning": "I’m allergic to nuts.", "mnemonic": "ALLERGISCH = allergic. Imagine showing your allergy card.", "level": 3},
{"word": "Ich fühle mich nicht gut.", "meaning": "I don’t feel well.", "mnemonic": "FÜHLEN = feel. Picture lying in bed looking pale.", "level": 3},
{"word": "Ich kann heute nicht kommen.", "meaning": "I can’t come today.", "mnemonic": "KANN NICHT = can't. Imagine cancelling a plan on your phone.", "level": 3},
{"word": "Ich bleibe lieber zu Hause.", "meaning": "I’d rather stay at home.", "mnemonic": "BLEIBE = stay. Picture relaxing at home instead of going out.", "level": 3},
{"word": "Ich muss früh aufstehen.", "meaning": "I have to get up early.", "mnemonic": "AUFSTEHEN = get up. Picture setting your alarm clock.", "level": 3},
{"word": "Ich möchte dich besser kennenlernen.", "meaning": "I’d like to get to know you better.", "mnemonic": "KENNENLERNEN = get to know. Picture a friendly coffee chat.", "level": 3},
{"word": "Ich habe keine Zeit.", "meaning": "I don’t have time.", "mnemonic": "KEINE ZEIT = no time. Picture rushing past a clock.", "level": 3},
{"word": "Ich habe gestern einen Film gesehen.", "meaning": "I watched a movie yesterday.", "mnemonic": "GESEHEN = seen. Picture a cinema ticket.", "level": 3},
{"word": "Ich muss jetzt gehen.", "meaning": "I have to go now.", "mnemonic": "MUSS = must, GEHEN = go. Imagine packing up quickly.", "level": 3},
{"word": "Wir treffen uns um acht Uhr.", "meaning": "We’re meeting at 8 o’clock.", "mnemonic": "TREFFEN = meet. Picture marking it in your calendar.", "level": 3},
{"word": "Ich habe morgen einen wichtigen Termin.", "meaning": "I have an important appointment tomorrow.", "mnemonic": "WICHTIG = important, TERMIN = appointment.", "level": 3},
{"word": "Ich habe keine Lust.", "meaning": "I don’t feel like it.", "mnemonic": "LUST = desire. Imagine sighing 'meh'.", "level": 3},
{"word": "Ich war noch nie in Deutschland.", "meaning": "I’ve never been to Germany.", "mnemonic": "NOCH NIE = never. Picture pointing to a blank on your map.", "level": 3},
{"word": "Ich esse kein Fleisch.", "meaning": "I don’t eat meat.", "mnemonic": "FLEISCH = meat. Picture politely declining a steak.", "level": 3},
{"word": "Ich bin Vegetarier.", "meaning": "I’m vegetarian.", "mnemonic": "Sounds like the English word – easy!", "level": 3},
{"word": "Können Sie mir bitte helfen?", "meaning": "Can you help me please?", "mnemonic": "HILFE = help. Think asking for directions.", "level": 3},
{"word": "Ich habe meinen Pass verloren.", "meaning": "I lost my passport.", "mnemonic": "PASS = passport. Imagine frantically checking your bag.", "level": 3},
{"word": "Ich brauche eine Fahrkarte nach München.", "meaning": "I need a ticket to Munich.", "mnemonic": "FAHRKARTE = ticket. Picture buying one at a station.", "level": 3},
{"word": "Ich spreche ein bisschen Deutsch.", "meaning": "I speak a little German.", "mnemonic": "BISSCHEN = little. Imagine trying your best in conversation.", "level": 3},
{"word": "Ich bin in Eile.", "meaning": "I’m in a hurry.", "mnemonic": "EILE = rush. Imagine running to catch a bus.", "level": 3},
{"word": "Ich möchte lieber etwas anderes.", "meaning": "I’d prefer something else.", "mnemonic": "ETWAS ANDERES = something else. Picture switching your order.", "level": 3},
{"word": "Ich hoffe, es gefällt dir.", "meaning": "I hope you like it.", "mnemonic": "GEFÄLLT = please. Picture offering someone a gift.", "level": 3},
{"word": "Ich habe viel zu tun.", "meaning": "I have a lot to do.", "mnemonic": "VIEL = much, TUN = to do. Picture a long to-do list.", "level": 3},
{"word": "Ich muss das später machen.", "meaning": "I have to do that later.", "mnemonic": "SPÄTER = later. Picture putting off a chore.", "level": 3},
{"word": "Ich wünsche dir einen schönen Tag.", "meaning": "I wish you a nice day.", "mnemonic": "WÜNSCHE = wish, SCHÖNEN TAG = nice day. A warm goodbye.", "level": 3},
{"word": "Kann ich mit Karte bezahlen?", "meaning": "Can I pay by card?", "mnemonic": "KARTE = card, BEZAHLEN = pay. Picture tapping your card.", "level": 3},
{"word": "Wie lange dauert der Flug?", "meaning": "How long is the flight?", "mnemonic": "DAUERT = lasts. Imagine checking the flight time online.", "level": 3},
{"word": "Was empfehlen Sie?", "meaning": "What do you recommend?", "mnemonic": "EMPFHLEN = recommend. Asking a waiter for advice.", "level": 3},
{"word": "Ich finde das interessant.", "meaning": "I find that interesting.", "mnemonic": "INTERESSANT = interesting – sounds just like it.", "level": 3},
{"word": "Ich kann ein bisschen lesen, aber nicht schreiben.", "meaning": "I can read a little, but not write.", "mnemonic": "LESEN = read, SCHREIBEN = write. Picture reading a menu but struggling to reply.", "level": 3},
{"word": "Ich freue mich auf das Wochenende.", "meaning": "I’m looking forward to the weekend.", "mnemonic": "FREUE MICH = I’m glad. Picture counting down to Friday!", "level": 3},
{"word": "Himmel", "meaning": "sky", "mnemonic": "HIMMEL sounds like 'heaven' – where the sky is.", "level": 1},
{"word": "Sonne", "meaning": "sun", "mnemonic": "SONNE shines like the sun with a warm ‘o’.", "level": 1},
{"word": "Regen", "meaning": "rain", "mnemonic": "REGEN falls like ‘rain’ with a German twist.", "level": 1},
{"word": "Schnee", "meaning": "snow", "mnemonic": "SCHNEE crunches underfoot like fresh snow.", "level": 1},
{"word": "Berg", "meaning": "mountain", "mnemonic": "BERG is a big, bulky mountain.", "level": 1},
{"word": "Fluss", "meaning": "river", "mnemonic": "FLUSS flows like a river with double ‘s’ waves.", "level": 1},
{"word": "Meer", "meaning": "sea", "mnemonic": "MEER mirrors the vast sea.", "level": 1},
{"word": "Wald", "meaning": "forest", "mnemonic": "WALD is a wall of trees in the forest.", "level": 1},
{"word": "Wolke", "meaning": "cloud", "mnemonic": "WOLKE floats like a fluffy cloud.", "level": 1},
{"word": "Stern", "meaning": "star", "mnemonic": "STERN twinkles like a star in the night.", "level": 1},
{"word": "Eis", "meaning": "ice", "mnemonic": "EIS sounds like 'ice' – think of slipping on icy EIS.", "level": 1},
    {"word": "Hut", "meaning": "hat", "mnemonic": "A HUT is a hat you wear in the sun.", "level": 1},
    {"word": "Ball", "meaning": "ball", "mnemonic": "BALL is the same in English – imagine bouncing it!", "level": 1},
    {"word": "Ring", "meaning": "ring", "mnemonic": "RING is a ring on your finger – just like English.", "level": 1},
    {"word": "Lied", "meaning": "song", "mnemonic": "LIED sounds like 'lied' (past tense of lie) – but it’s a song you sing truthfully!", "level": 1},
    {"word": "Tasche", "meaning": "bag", "mnemonic": "TASCHE rhymes with 'satchel' – a type of bag.", "level": 1},
    {"word": "Luft", "meaning": "air", "mnemonic": "LUFT sounds like 'loft' – where air circulates.", "level": 1},
    {"word": "Raum", "meaning": "room", "mnemonic": "RAUM is like 'room' with a cosmic twist (think 'space room').", "level": 1},
    {"word": "Licht", "meaning": "light", "mnemonic": "LICHT is what turns on when you flick the light switch.", "level": 1},
    {"word": "Nacht", "meaning": "night", "mnemonic": "NACHT sounds like 'knocked' – you sleep at night.", "level": 1},
    {"word": "Tag", "meaning": "day", "mnemonic": "TAG is the day you play tag outside.", "level": 1},
    {"word": "Monat", "meaning": "month", "mnemonic": "MONAT sounds like 'moon at' – a month is a moon cycle.", "level": 1},
    {"word": "Jahr", "meaning": "year", "mnemonic": "JAHR sounds like 'yahr' (German 'j' is a 'y' sound).", "level": 1},
    {"word": "Zeit", "meaning": "time", "mnemonic": "ZEIT is time ticking away ('Zeitgeist' = spirit of the time).", "level": 1},
    {"word": "Name", "meaning": "name", "mnemonic": "NAME is the same in English – easy!", "level": 1},
    {"word": "Ort", "meaning": "place", "mnemonic": "ORT is your 'port' to a new place.", "level": 1},
    {"word": "Land", "meaning": "country", "mnemonic": "LAND is the land you live in (e.g., Deutschland).", "level": 1},
    {"word": "Stadt", "meaning": "city", "mnemonic": "STADT is where the streets are stacked with buildings.", "level": 1},
    {"word": "Dorf", "meaning": "village", "mnemonic": "DORF sounds like 'dwarf' – tiny like a village.", "level": 1},
    {"word": "Flügel", "meaning": "wing", "mnemonic": "FLÜGEL sounds like 'flying gel' – wings help you fly.", "level": 1},
    {"word": "Feder", "meaning": "feather", "mnemonic": "FEDER is a feather floating down.", "level": 1},
    {"word": "Haut", "meaning": "skin", "mnemonic": "HAUT sounds like 'hot' – your skin feels heat.", "level": 1},
    {"word": "Arm", "meaning": "arm", "mnemonic": "ARM is the same in English – wave your ARM!", "level": 1},
    {"word": "Bein", "meaning": "leg", "mnemonic": "BEIN sounds like 'bone' – legs have bones.", "level": 1},
    {"word": "Finger", "meaning": "finger", "mnemonic": "FINGER is almost the same in English.", "level": 1},
    {"word": "Zeh", "meaning": "toe", "mnemonic": "ZEH sounds like 'say' – say 'hi' with your toes!", "level": 1},
    {"word": "Rücken", "meaning": "back", "mnemonic": "RÜCKEN sounds like 'ruckus' – a sore back causes a ruckus.", "level": 1},
    {"word": "Bauch", "meaning": "belly", "mnemonic": "BAUCH sounds like 'bow' – your belly bends when you bow.", "level": 1},
    {"word": "Hals", "meaning": "neck", "mnemonic": "HALS sounds like 'halls' – imagine your neck as a hallway.", "level": 1},
    {"word": "Knie", "meaning": "knee", "mnemonic": "KNIE is like 'knee' with an 'ee' sound.", "level": 1},
    {"word": "Fuß", "meaning": "foot", "mnemonic": "FUß is a foot stepping in ß (sharp 's')now.", "level": 1},
    {"word": "Auge", "meaning": "eye", "mnemonic": "AUGE sounds like 'ogre' – big eyes!", "level": 1},
    {"word": "Ohr", "meaning": "ear", "mnemonic": "OHR sounds like 'oar' – row your oar to your ear.", "level": 1},
    {"word": "Nase", "meaning": "nose", "mnemonic": "NASE sounds like 'nuzzle' – nuzzle with your nose.", "level": 1},
    {"word": "Mund", "meaning": "mouth", "mnemonic": "MUND sounds like 'munch' – use your mouth to munch.", "level": 1},
    {"word": "Zahn", "meaning": "tooth", "mnemonic": "ZAHN sounds like 'yawn' – show your teeth when you yawn.", "level": 1},
    {"word": "Lippe", "meaning": "lip", "mnemonic": "LIPPE is like 'lip' with extra pep.", "level": 1},
    {"word": "Hand", "meaning": "hand", "mnemonic": "HAND is the same in English – high five!", "level": 1},
    {"word": "Kopf", "meaning": "head", "mnemonic": "KOPF sounds like 'cup' – imagine a cup on your head.", "level": 1},
    {"word": "Herz", "meaning": "heart", "mnemonic": "HERZ is the heart beating hard.", "level": 1},
    {"word": "Blut", "meaning": "blood", "mnemonic": "BLUT sounds like 'bloom' – blood flows like blooming flowers.", "level": 1},
    {"word": "Knochen", "meaning": "bone", "mnemonic": "KNOCHEN sounds like 'knockin’' – bones knock together.", "level": 1},
    {"word": "Muschel", "meaning": "shell", "mnemonic": "MUSCHEL sounds like 'mussel' – a seashell.", "level": 1},
    {"word": "Stern", "meaning": "star", "mnemonic": "STERN is a star burning brightly.", "level": 1},
    {"word": "Hügel", "meaning": "hill", "mnemonic": "HÜGEL sounds like 'huggle' – a hill you hug as you climb.", "level": 1},
    {"word": "Stein", "meaning": "stone", "mnemonic": "STEIN is a stone you stumble on.", "level": 1},
    {"word": "Sand", "meaning": "sand", "mnemonic": "SAND is the same in English – think of the beach.", "level": 1},
    {"word": "Welle", "meaning": "wave", "mnemonic": "WELLE is a wave rolling in the sea.", "level": 1},
    {"word": "Feuer", "meaning": "fire", "mnemonic": "FEUER sounds like 'fury' – fire is furious!", "level": 1},
    {"word": "Rauch", "meaning": "smoke", "mnemonic": "RAUCH sounds like 'rough' – smoke is rough on your lungs.", "level": 1},
    {"word": "Wasser", "meaning": "water", "mnemonic": "WASSER is water splashing.", "level": 1}
]